# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-25 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
