# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-25 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='all_users',
            field=models.ManyToManyField(related_name='all_items', to='wishlist.users'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='curr_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishitem', to='wishlist.users'),
            preserve_default=False,
        ),
    ]
